### ISSUE TITLE
unable to find an inherited method for function ‘annotation’ for signature ‘"character"’

### ISSUE THREAD

**Issue by andy-shaps** [alexvpickering/crossmeta#13] opened 2022-05-24 10:12 UTC
Hi, 

I have an issue following the tutorial on github. The `load_raw()` function produces error: "unable to find an inherited method for function ‘annotation’ for signature ‘"character"'".

I have tried installing from Bioconductor (v 1.22.0) and GitHub (which surprisingly is an earlier version v 1.21.4) but seem to have the issue in both.

I have reinstalled and ensured it installed with no warnings. 

Many thanks,

```
> sessionInfo()
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8    LC_MONETARY=English_United Kingdom.utf8
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] crossmeta_1.22.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3        digest_0.6.29       later_1.3.0         mime_0.12           R6_2.5.1            lifecycle_1.0.1     xtable_1.8-4       
 [8] magrittr_2.0.3      rlang_1.0.2         cli_3.3.0           miniUI_0.1.1.1      data.table_1.14.2   promises_1.2.0.1    ellipsis_0.3.2     
[15] shinyjs_2.1.0       tools_4.2.0         Biobase_2.56.0      shiny_1.7.1         httpuv_1.6.5        fastmap_1.1.0       compiler_4.2.0     
[22] BiocGenerics_0.42.0 htmltools_0.5.2  
```

**Comment by alexvpickering** [comment] 2022-05-24 15:32
Hi Andy,

Bioconductor bumps version according to their release schedule so I would guess that is the reason for the version differences. Github definitely has the latest changes. 

Thanks for the report, I was able to reproduce. The issue was due to changes in GEO (an added link in the GEO Matrix listing). Should be fixed now (https://github.com/alexvpickering/crossmeta/commit/5515233b37135c676cd496ef1ccaf7c79a9808b0). Let me know.

**Comment by andy-shaps** [comment] 2022-05-25 14:41
Hi Alex,

Thanks for the reply. I am getting a new error after updating to v 1.23.2.

```
> esets <- load_raw(gse_names)
Found 1 file(s)
GSE9601_series_matrix.txt.gz
Found 1 file(s)
GSE9601_series_matrix.txt.gz
Using locally cached version: C:/Users/User/Documents/GSE9601/GSE9601_series_matrix.txt.gz
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Loading required package: pd.hg.u95av2
Attempting to obtain 'pd.hg.u95av2' from BioConductor website.
Checking to see if your internet connection works...
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Error: GSE9601 (1 of 1): unable to find an inherited method for function ‘rma’ for signature ‘"NULL"’

Found 1 file(s)
GSE15069_series_matrix.txt.gz
Found 1 file(s)
GSE15069_series_matrix.txt.gz
Using locally cached version: C:/Users/User/Documents/GSE15069/GSE15069_series_matrix.txt.gz
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Loading required package: pd.mouse430.2
Attempting to obtain 'pd.mouse430.2' from BioConductor website.
Checking to see if your internet connection works...
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Error: GSE15069 (1 of 1): unable to find an inherited method for function ‘rma’ for signature ‘"NULL"’
```

**Comment by alexvpickering** [comment] 2022-05-25 14:57
Hi Andy,

I'm not able to reproduce this issue. Maybe check that installation of the cdf packages occured (`mouse4302cdf` and `hgu95av2cdf`). Also make sure your starting from a clean `data_dir` in the call to `get_raw`.  Both datasets load for me:

```R
> library(crossmeta)
> gse_names <- 'GSE9601'
> get_raw(gse_names)
trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE9nnn/GSE9601/suppl//GSE9601_RAW.tar?tool=geoquery'
Content type 'application/x-tar' length 40704000 bytes (38.8 MB)
==================================================
downloaded 38.8 MB

> blah <- load_raw(gse_names)
Found 1 file(s)
GSE9601_series_matrix.txt.gz
Found 1 file(s)
GSE9601_series_matrix.txt.gz
Using locally cached version: /home/alex/Documents/Batcave/GEO/crossmeta/GSE9601/GSE9601_series_matrix.txt.gz

Background correcting
Normalizing
Calculating Expression
Annotating
Warning messages:
1: replacing previous import ‘AnnotationDbi::tail’ by ‘utils::tail’ when loading ‘hgu95av2cdf’ 
2: replacing previous import ‘AnnotationDbi::head’ by ‘utils::head’ when loading ‘hgu95av2cdf’ 
> blah
$GSE9601
ExpressionSet (storageMode: lockedEnvironment)
assayData: 13480 features, 12 samples 
  element names: exprs 
protocolData: none
phenoData
  sampleNames: GSM242894 GSM242895 ... GSM242905 (12 total)
  varLabels: title geo_accession ... Virus Strain:ch1 (39 total)
  varMetadata: labelDescription
featureData
  featureNames: 1000_at 1001_at ... AFFX-hum_alu_at (13480 total)
  fvarLabels: ENTREZID PROBE ... SYMBOL (5 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
Annotation: GPL8300 

> gse_names <- 'GSE15069'
> get_raw(gse_names)
trying URL 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE15nnn/GSE15069/suppl//GSE15069_RAW.tar?tool=geoquery'
Content type 'application/x-tar' length 66938880 bytes (63.8 MB)
==================================================
downloaded 63.8 MB

> blah <- load_raw(gse_names)
Found 1 file(s)
GSE15069_series_matrix.txt.gz
Found 1 file(s)
GSE15069_series_matrix.txt.gz
Using locally cached version: /home/alex/Documents/Batcave/GEO/crossmeta/GSE15069/GSE15069_series_matrix.txt.gz
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

trying URL 'https://bioconductor.org/packages/3.14/data/annotation/src/contrib/mouse4302cdf_2.18.0.tar.gz'
Content type 'application/x-gzip' length 3531403 bytes (3.4 MB)
==================================================
downloaded 3.4 MB

* installing *source* package ‘mouse4302cdf’ ...
** using staged installation
** R
** data
** byte-compile and prepare package for lazy loading
Warning: replacing previous import ‘AnnotationDbi::tail’ by ‘utils::tail’ when loading ‘mouse4302cdf’
Warning: replacing previous import ‘AnnotationDbi::head’ by ‘utils::head’ when loading ‘mouse4302cdf’
** help
*** installing help indices
  converting help for package ‘mouse4302cdf’
    finding HTML links ... done
    geometry                                html  
    mouse4302cdf                            html  
    mouse4302dim                            html  
** building package indices
** testing if installed package can be loaded from temporary location
Warning: replacing previous import ‘AnnotationDbi::tail’ by ‘utils::tail’ when loading ‘mouse4302cdf’
Warning: replacing previous import ‘AnnotationDbi::head’ by ‘utils::head’ when loading ‘mouse4302cdf’
** testing if installed package can be loaded from final location
Warning: replacing previous import ‘AnnotationDbi::tail’ by ‘utils::tail’ when loading ‘mouse4302cdf’
Warning: replacing previous import ‘AnnotationDbi::head’ by ‘utils::head’ when loading ‘mouse4302cdf’
** testing if installed package keeps a record of temporary installation path
* DONE (mouse4302cdf)

The downloaded source packages are in
	‘/tmp/Rtmp8BTADP/downloaded_packages’


Attaching package: ‘mouse4302cdf’

The following objects are masked from ‘package:hgu95av2cdf’:

    i2xy, xy2i

Background correcting
Normalizing
Calculating Expression
Annotating'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.14 (BiocManager 1.30.16), R 4.1.3 (2022-03-10)
Installing package(s) 'mouse430a2.db'
trying URL 'https://bioconductor.org/packages/3.14/data/annotation/src/contrib/mouse430a2.db_3.13.0.tar.gz'
Content type 'application/x-gzip' length 940908 bytes (918 KB)
==================================================
downloaded 918 KB

* installing *source* package ‘mouse430a2.db’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package ‘mouse430a2.db’
    finding HTML links ... done
    mouse430a2ACCNUM                        html  
    mouse430a2ALIAS2PROBE                   html  
    mouse430a2BASE                          html  
    mouse430a2CHR                           html  
    mouse430a2CHRLENGTHS                    html  
    mouse430a2CHRLOC                        html  
    mouse430a2ENSEMBL                       html  
    mouse430a2ENTREZID                      html  
    mouse430a2ENZYME                        html  
    mouse430a2GENENAME                      html  
    mouse430a2GO                            html  
    mouse430a2MAPCOUNTS                     html  
    mouse430a2MGI                           html  
    mouse430a2ORGANISM                      html  
    mouse430a2PATH                          html  
    mouse430a2PFAM                          html  
    mouse430a2PMID                          html  
    mouse430a2PROSITE                       html  
    mouse430a2REFSEQ                        html  
    mouse430a2SYMBOL                        html  
    mouse430a2UNIPROT                       html  
    mouse430a2_dbconn                       html  
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (mouse430a2.db)

The downloaded source packages are in
	‘/tmp/Rtmp8BTADP/downloaded_packages’

Warning messages:
1: replacing previous import ‘AnnotationDbi::tail’ by ‘utils::tail’ when loading ‘mouse4302cdf’ 
2: replacing previous import ‘AnnotationDbi::head’ by ‘utils::head’ when loading ‘mouse4302cdf’ 
> blah
$GSE15069
ExpressionSet (storageMode: lockedEnvironment)
assayData: 46604 features, 15 samples 
  element names: exprs 
protocolData: none
phenoData
  sampleNames: GSM376950 GSM376951 ... GSM377052 (15 total)
  varLabels: title geo_accession ... tissue:ch1 (43 total)
  varMetadata: labelDescription
featureData
  featureNames: 1415670_at 1415671_at ... AFFX-r2-P1-cre-5_at (46604 total)
  fvarLabels: ENTREZID PROBE ... SYMBOL (5 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
Annotation: GPL1261 

```

**Comment by andy-shaps** [comment] 2022-05-26 12:52
Hi Alex,

It appears as though `mouse4302cdf` and `hgu95av2cdf` didn't install. not quite sure why? After manual installation the error goes away.

Thanks for helping solve this issue.

**Comment by alexvpickering** [comment] 2022-05-27 20:35
> Hi Alex,
> 
> It appears as though `mouse4302cdf` and `hgu95av2cdf` didn't install. not quite sure why? After manual installation the error goes away.
> 
> Thanks for helping solve this issue.

Hi Andy, there was likely an issue with your internet connection and the error wasn't thrown. In particular, your messages show the following:

```R
Loading required package: pd.hg.u95av2
Attempting to obtain 'pd.hg.u95av2' from BioConductor website.
Checking to see if your internet connection works...
```
This particular annotation package (`pd.hg.u95av2`) is automatically downloaded by a call to `oligo::read.celfiles` here:

https://github.com/alexvpickering/crossmeta/blob/0349744e9eeb37a176015f201063a8f09954bbae/R/load_affy.R#L101

`oligo::read.celfiles` is called as a backup in case `affy::ReadAffy` fails to load the Affymetrix CEL files just above:

https://github.com/alexvpickering/crossmeta/blob/0349744e9eeb37a176015f201063a8f09954bbae/R/load_affy.R#L62-L66

Because of the connection issue, the initial call to `affy::ReadAffy` itself also failed to download the annotation package that it required (`hgu95av2cdf`).

I've gone ahead and pushed some changes so that these failures boil up. Thanks for the report! Let me know if you have any further issues

**Closed as completed** 2022-05-31 21:08 UTC
